version: '3.7'

networks:
  paaspop_bridge:
    name: paaspop_bridge
    driver: bridge

services:
  # uwebsockets for socket connections
  websocket_server:
    container_name: uwebsockets
    build:
      context: ./uwebsockets
    ports:
      - 9000:9000
    networks:
      - paaspop_bridge
  # Admin panel vor VJ crew
  admin_panel:
    build:
      context: ./adminpanel
    container_name: adminpanel
    depends_on:
      - db
      - nginx
    networks:
      - paaspop_bridge
    expose:
      - "8080"
  db:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - paaspop_bridge
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: paaspopadminaccount
      MONGO_INITDB_ROOT_PASSWORD: J836jlXcJW2JgLDQdiBz
      MONGO_INITDB_DATABASE: paaspopserver
    volumes:
      - ./data/db:/data/db
    ports:
        - 27018:27018
  nginx:
    build:
      context: ./nginx
    logging:
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - paaspop_bridge
    ports:
      - '80:80'
      - '5454:5454'
    restart: on-failure